#!/usr/bin/env python
import sys

from PySide.QtGui import QApplication
from PySide.QtCore import QTimer

import ui
import xibo
import argparse

if __name__ == '__main__':
    config_file = 'xiboside_config.json'
    parser = argparse.ArgumentParser(
        description="xiboside, a Xibo Player"
    )
    parser.add_argument(
        '-c', '--config', default=config_file,
        help="Configuration file, default is %s" % config_file
    )
    args = parser.parse_args()

    app = QApplication(sys.argv)
    rect = app.desktop().screenGeometry()
    cfg = xibo.XiboConfig(args.config)

    ret = -1
    with ui.MainWindow(cfg) as w:
        # fullscreen delay timer
        ft = QTimer()
        ft.setSingleShot(True)
        ft.timeout.connect(w.showFullScreen)
        ft.start(1000)

        w.setGeometry(rect)
        w.show()
        ret = app.exec_()
        print 'Exiting, please wait...'
    print 'Saving configuration to %s' % cfg.path
    cfg.save()
    sys.exit(ret)
