#!/usr/bin/env python
import sys
import os
from PySide.QtGui import QApplication
from PySide.QtCore import QTimer

import ui
import xibo
import argparse

if __name__ == '__main__':
    config_file = 'xiboside_config.json'

    parser = argparse.ArgumentParser(
        description="xiboside, a Xibo Player"
    )
    parser.add_argument(
        '-c', '--config', default=config_file,
        help="Configuration file, default is %s" % config_file
    )
    args = parser.parse_args()

    app = QApplication(sys.argv)
    rect = app.desktop().screenGeometry()
    cfg = xibo.XiboConfig(args.config)

    if not os.path.isfile(args.config):
        print
        print '  The configuration file %s is not exists' % args.config
        print '  Creating default configuration...'
        cfg.save()
        print "  Please edit the '%s' file and then rerun xiboside again" % args.config
        print
        sys.exit(0)

    ret = -1
    with ui.MainWindow(cfg) as w:
        # fullscreen delay timer
        ft = QTimer()
        ft.setSingleShot(True)
        ft.timeout.connect(w.showFullScreen)
        ft.start(1000)

        w.setGeometry(rect)
        w.show()
        ret = app.exec_()
        print 'Exiting, please wait...'
    print 'Saving configuration to %s' % cfg.path
    cfg.save()
    sys.exit(ret)
